### ISSUE TITLE
BlockEntity Wont Load 

### ISSUE THREAD

**Issue by MagicMikey6** [Tutorials-By-Kaupenjoe/Forge-Tutorial-1.20.X#15]
I did the block entity tuto and the block wont /give and when in invetory tab crashed when i open my inventory?

**Comment by MagicMikey6** [comment]
|:

**Comment by MagicMikey6** [comment]
Please Help ):
I Tried Everything I Could!

**Comment by SashaKYotoz** [comment]
You probably missed registration of some DeferredRegister. To be possible to help you rather send your crash logs

**Comment by MagicMikey6** [comment]
this is fixed and has been on the same day posted forgot to close
